import { ReduxToolkitProvider } from "@/app/provider"
import "../../(main)/global.scss"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxToolkitProvider>
      <html lang="ru">
        <body>
          <main>
            <p>ТЕСТ</p>
            {children}
          </main>
        </body>
      </html>
    </ReduxToolkitProvider>
  )
}
