import "@/app/global.scss"
import { ReduxToolkitProvider } from "./provider"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ReduxToolkitProvider>
      <html lang="ru">
        <body style={{ minHeight: "100vh" }}>
          {children}
        </body>
      </html>
    </ReduxToolkitProvider>
  )
}
