import { Header } from "@/components/Header/Header"
import "./global.scss"
import { ReduxToolkitProvider } from "../../provider"
import { Footer } from "@/components/Footer/Footer"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxToolkitProvider>
      <html lang="ru">
        <body>
          <Header/>
          <main>
            
            {children}
          </main>
          <Footer/>
        </body>
      </html>
    </ReduxToolkitProvider>
  )
}
